/**********************************************************************
 * Extern for ReactBootstrapTable
 * Generated by http://jmmk.github.io/javascript-externs-generator
 **********************************************************************/
var ReactBootstrapTable = {
  "BootstrapTable": {
    "defaultProps": {
      "autoCollapse": {
        "filter": {},
        "search": {},
        "sort": {}
      },
      "bodyContainerClass": {},
      "bodyStyle": {},
      "bordered": {},
      "cellEdit": {
        "afterSaveCell": {},
        "beforeSaveCell": {},
        "blurToEscape": {},
        "blurToSave": {},
        "mode": {},
        "nonEditableRows": {}
      },
      "columnFilter": {},
      "condensed": {},
      "containerClass": {},
      "containerStyle": {},
      "csvFileName": {},
      "deleteRow": {},
      "expandColumnOptions": {
        "expandColumnBeforeSelectColumn": {},
        "expandColumnComponent": {},
        "expandColumnVisible": {}
      },
      "expandComponent": {},
      "expandableRow": {},
      "exportCSV": {},
      "fetchInfo": {
        "dataTotalSize": {}
      },
      "headerContainerClass": {},
      "headerStyle": {},
      "height": {},
      "hover": {},
      "ignoreSinglePage": {},
      "insertRow": {},
      "keyBoardNav": {},
      "maxHeight": {},
      "multiColumnSearch": {},
      "multiColumnSort": {},
      "options": {
        "afterColumnFilter": {},
        "afterDeleteRow": {},
        "afterInsertRow": {},
        "afterSearch": {},
        "afterTableComplete": {},
        "alwaysShowAllBtns": {},
        "beforeShowError": {},
        "btnGroup": {},
        "clearSearch": {},
        "clearSearchBtn": {},
        "closeText": {},
        "defaultSearch": {},
        "defaultSortName": {},
        "defaultSortOrder": {},
        "deleteBtn": {},
        "deleteText": {},
        "excludeCSVHeader": {},
        "expandBodyClass": {},
        "expandBy": {},
        "expandParentClass": {},
        "expandRowBgColor": {},
        "expanding": {},
        "exportCSVBtn": {},
        "exportCSVSeparator": {},
        "exportCSVText": {},
        "firstPage": {},
        "firstPageTitle": {},
        "handleConfirmDeleteRow": {},
        "hidePageListOnlyOnePage": {},
        "hideSizePerPage": {},
        "ignoreEditable": {},
        "insertBtn": {},
        "insertFailIndicator": {},
        "insertModal": {},
        "insertModalBody": {},
        "insertModalFooter": {},
        "insertModalHeader": {},
        "insertText": {},
        "keepSizePerPageState": {},
        "lastPage": {},
        "lastPageTitle": {},
        "nextPage": {},
        "nextPageTitle": {},
        "noAutoBOM": {},
        "noDataText": {},
        "onExpand": {},
        "onMouseEnter": {},
        "onMouseLeave": {},
        "onRowClick": {},
        "onRowDoubleClick": {},
        "onRowMouseOut": {},
        "onRowMouseOver": {},
        "onSizePerPageList": {},
        "onlyOneExpanding": {},
        "page": {},
        "pageStartIndex": {},
        "paginationPanel": {},
        "paginationPosition": {},
        "paginationShowsTotal": {},
        "paginationSize": {},
        "prePage": {},
        "prePageTitle": {},
        "printToolBar": {},
        "saveText": {},
        "searchDelayTime": {},
        "searchField": {},
        "searchPanel": {},
        "searchPosition": {},
        "showSelectedOnlyBtn": {},
        "sizePerPage": {},
        "sizePerPageDropDown": {},
        "sizePerPageList": {},
        "sortIndicator": {},
        "sortName": {},
        "sortOrder": {},
        "toolBar": {},
        "toolbarPosition": {},
        "withFirstAndLast": {},
        "withoutNoDataText": {}
      },
      "pagination": {},
      "printable": {},
      "replace": {},
      "scrollTop": {},
      "search": {},
      "searchPlaceholder": {},
      "selectRow": {
        "bgColor": {},
        "clickToExpand": {},
        "clickToSelect": {},
        "clickToSelectAndEditCell": {},
        "customComponent": {},
        "hideSelectColumn": {},
        "mode": {},
        "onSelect": {},
        "onSelectAll": {},
        "onlyUnselectVisible": {},
        "selected": {},
        "showOnlySelected": {},
        "unselectable": {}
      },
      "strictSearch": {},
      "striped": {},
      "tableBodyClass": {},
      "tableContainerClass": {},
      "tableHeaderClass": {},
      "tableStyle": {},
      "trClassName": {},
      "trStyle": {},
      "version": {},
      "withoutTabIndex": {}
    },
    "propTypes": {
      "autoCollapse": {
        "isRequired": function () {}
      },
      "bodyContainerClass": {
        "isRequired": function () {}
      },
      "bodyStyle": {
        "isRequired": function () {}
      },
      "bordered": {
        "isRequired": function () {}
      },
      "cellEdit": {
        "isRequired": function () {}
      },
      "columnFilter": {
        "isRequired": function () {}
      },
      "condensed": {
        "isRequired": function () {}
      },
      "containerClass": {
        "isRequired": function () {}
      },
      "containerStyle": {
        "isRequired": function () {}
      },
      "csvFileName": {
        "isRequired": function () {}
      },
      "data": {
        "isRequired": function () {}
      },
      "deleteRow": {
        "isRequired": function () {}
      },
      "expandColumnOptions": {
        "isRequired": function () {}
      },
      "expandComponent": {
        "isRequired": function () {}
      },
      "expandableRow": {
        "isRequired": function () {}
      },
      "exportCSV": {
        "isRequired": function () {}
      },
      "fetchInfo": {
        "isRequired": function () {}
      },
      "headerContainerClass": {
        "isRequired": function () {}
      },
      "headerStyle": {
        "isRequired": function () {}
      },
      "height": {
        "isRequired": function () {}
      },
      "hover": {
        "isRequired": function () {}
      },
      "ignoreSinglePage": {
        "isRequired": function () {}
      },
      "insertRow": {
        "isRequired": function () {}
      },
      "keyBoardNav": {
        "isRequired": function () {}
      },
      "keyField": {
        "isRequired": function () {}
      },
      "maxHeight": {
        "isRequired": function () {}
      },
      "multiColumnSearch": {
        "isRequired": function () {}
      },
      "options": {
        "isRequired": function () {}
      },
      "pagination": {
        "isRequired": function () {}
      },
      "printable": {
        "isRequired": function () {}
      },
      "remote": {
        "isRequired": function () {}
      },
      "replace": {
        "isRequired": function () {}
      },
      "scrollTop": {
        "isRequired": function () {}
      },
      "search": {
        "isRequired": function () {}
      },
      "searchPlaceholder": {
        "isRequired": function () {}
      },
      "selectRow": {
        "isRequired": function () {}
      },
      "strictSearch": {
        "isRequired": function () {}
      },
      "striped": {
        "isRequired": function () {}
      },
      "tableBodyClass": {
        "isRequired": function () {}
      },
      "tableContainerClass": {
        "isRequired": function () {}
      },
      "tableHeaderClass": {
        "isRequired": function () {}
      },
      "tableStyle": {
        "isRequired": function () {}
      },
      "trClassName": {
        "isRequired": function () {}
      },
      "trStyle": {
        "isRequired": function () {}
      },
      "version": {
        "isRequired": function () {}
      },
      "withoutTabIndex": {
        "isRequired": function () {}
      }
    }
  },
  "ButtonGroup": {
    "defaultProps": {
      "className": {},
      "sizeClass": {}
    },
    "propTypes": {
      "className": {
        "isRequired": function () {}
      },
      "sizeClass": {
        "isRequired": function () {}
      }
    }
  },
  "ClearSearchButton": {
    "defaultProps": {
      "btnContextual": {},
      "btnText": {},
      "className": {},
      "onClick": {}
    },
    "propTypes": {
      "btnContextual": {
        "isRequired": function () {}
      },
      "btnText": {
        "isRequired": function () {}
      },
      "className": {
        "isRequired": function () {}
      },
      "onClick": {
        "isRequired": function () {}
      }
    }
  },
  "DeleteButton": {
    "defaultProps": {
      "btnContextual": {},
      "btnGlyphicon": {},
      "btnText": {},
      "className": {},
      "onClick": {}
    },
    "propTypes": {
      "btnContextual": {
        "isRequired": function () {}
      },
      "btnGlyphicon": {
        "isRequired": function () {}
      },
      "btnText": {
        "isRequired": function () {}
      },
      "className": {
        "isRequired": function () {}
      },
      "onClick": {
        "isRequired": function () {}
      }
    }
  },
  "ExportCSVButton": {
    "defaultProps": {
      "btnContextual": {},
      "btnGlyphicon": {},
      "btnText": {},
      "className": {},
      "onClick": {}
    },
    "propTypes": {
      "btnContextual": {
        "isRequired": function () {}
      },
      "btnGlyphicon": {
        "isRequired": function () {}
      },
      "btnText": {
        "isRequired": function () {}
      },
      "className": {
        "isRequired": function () {}
      },
      "onClick": {
        "isRequired": function () {}
      }
    }
  },
  "InsertButton": {
    "defaultProps": {
      "btnContextual": {},
      "btnGlyphicon": {},
      "btnText": {},
      "className": {},
      "onClick": {}
    },
    "propTypes": {
      "btnContextual": {
        "isRequired": function () {}
      },
      "btnGlyphicon": {
        "isRequired": function () {}
      },
      "btnText": {
        "isRequired": function () {}
      },
      "className": {
        "isRequired": function () {}
      },
      "onClick": {
        "isRequired": function () {}
      }
    }
  },
  "InsertModalBody": {
    "defaultProps": {
      "ignoreEditable": {},
      "validateState": {}
    },
    "propTypes": {
      "columns": {
        "isRequired": function () {}
      },
      "ignoreEditable": {
        "isRequired": function () {}
      },
      "validateState": {
        "isRequired": function () {}
      }
    }
  },
  "InsertModalFooter": {
    "defaultProps": {
      "beforeClose": {},
      "beforeSave": {},
      "className": {},
      "closeBtnClass": {},
      "closeBtnContextual": {},
      "closeBtnText": {},
      "saveBtnClass": {},
      "saveBtnContextual": {},
      "saveBtnText": {}
    },
    "propTypes": {
      "beforeClose": {
        "isRequired": function () {}
      },
      "beforeSave": {
        "isRequired": function () {}
      },
      "className": {
        "isRequired": function () {}
      },
      "closeBtnClass": {
        "isRequired": function () {}
      },
      "closeBtnContextual": {
        "isRequired": function () {}
      },
      "closeBtnText": {
        "isRequired": function () {}
      },
      "onModalClose": {
        "isRequired": function () {}
      },
      "onSave": {
        "isRequired": function () {}
      },
      "saveBtnClass": {
        "isRequired": function () {}
      },
      "saveBtnContextual": {
        "isRequired": function () {}
      },
      "saveBtnText": {
        "isRequired": function () {}
      }
    }
  },
  "InsertModalHeader": {
    "defaultProps": {
      "beforeClose": {},
      "className": {},
      "hideClose": {},
      "onModalClose": {},
      "title": {},
      "version": {}
    },
    "propTypes": {
      "beforeClose": {
        "isRequired": function () {}
      },
      "className": {
        "isRequired": function () {}
      },
      "hideClose": {
        "isRequired": function () {}
      },
      "onModalClose": {
        "isRequired": function () {}
      },
      "title": {
        "isRequired": function () {}
      },
      "version": {
        "isRequired": function () {}
      }
    }
  },
  "SearchField": {
    "defaultProps": {
      "className": {},
      "defaultValue": {},
      "onKeyUp": {},
      "placeholder": {}
    },
    "propTypes": {
      "className": {
        "isRequired": function () {}
      },
      "defaultValue": {
        "isRequired": function () {}
      },
      "onKeyUp": {
        "isRequired": function () {}
      },
      "placeholder": {
        "isRequired": function () {}
      }
    }
  },
  "ShowSelectedOnlyButton": {
    "defaultProps": {
      "btnContextual": {},
      "className": {},
      "onClick": {},
      "showAllText": {},
      "showOnlySelectText": {},
      "toggle": {}
    },
    "propTypes": {
      "btnContextual": {
        "isRequired": function () {}
      },
      "className": {
        "isRequired": function () {}
      },
      "onClick": {
        "isRequired": function () {}
      },
      "showAllText": {
        "isRequired": function () {}
      },
      "showOnlySelectText": {
        "isRequired": function () {}
      },
      "toggle": {
        "isRequired": function () {}
      }
    }
  },
  "SizePerPageDropDown": {
    "defaultProps": {
      "btnContextual": {},
      "className": {},
      "hidden": {},
      "open": {},
      "variation": {}
    },
    "propTypes": {
      "btnContextual": {
        "isRequired": function () {}
      },
      "className": {
        "isRequired": function () {}
      },
      "currSizePerPage": {
        "isRequired": function () {}
      },
      "hidden": {
        "isRequired": function () {}
      },
      "onClick": {
        "isRequired": function () {}
      },
      "open": {
        "isRequired": function () {}
      },
      "options": {
        "isRequired": function () {}
      },
      "variation": {
        "isRequired": function () {}
      }
    }
  },
  "TableHeaderColumn": {
    "defaultProps": {
      "className": {},
      "columnClassName": {},
      "columnTitle": {},
      "csvFieldType": {},
      "csvFormat": {},
      "csvHeader": {},
      "dataAlign": {},
      "dataFormat": {},
      "dataSort": {},
      "defaultASC": {},
      "editColumnClassName": {},
      "editTdAttr": {},
      "editable": {},
      "expandable": {},
      "filter": {},
      "filterFormatted": {},
      "filterValue": {},
      "formatExtraData": {},
      "headerAlign": {},
      "headerTitle": {},
      "hidden": {},
      "hiddenOnInsert": {},
      "invalidEditColumnClassName": {},
      "isKey": {},
      "keyValidator": {},
      "onSort": {},
      "searchable": {},
      "sort": {},
      "sortFunc": {},
      "sortFuncExtraData": {},
      "sortIndicator": {},
      "tdAttr": {},
      "tdStyle": {},
      "thStyle": {},
      "width": {}
    },
    "propTypes": {
      "caretRender": {
        "isRequired": function () {}
      },
      "className": {
        "isRequired": function () {}
      },
      "columnClassName": {
        "isRequired": function () {}
      },
      "columnTitle": {
        "isRequired": function () {}
      },
      "csvFieldType": {
        "isRequired": function () {}
      },
      "csvFormat": {
        "isRequired": function () {}
      },
      "csvFormatExtraData": {
        "isRequired": function () {}
      },
      "csvHeader": {
        "isRequired": function () {}
      },
      "dataAlign": {
        "isRequired": function () {}
      },
      "dataField": {
        "isRequired": function () {}
      },
      "dataFormat": {
        "isRequired": function () {}
      },
      "dataSort": {
        "isRequired": function () {}
      },
      "defaultASC": {
        "isRequired": function () {}
      },
      "editColumnClassName": {
        "isRequired": function () {}
      },
      "editTdAttr": {
        "isRequired": function () {}
      },
      "editable": {
        "isRequired": function () {}
      },
      "expandable": {
        "isRequired": function () {}
      },
      "export": {
        "isRequired": function () {}
      },
      "filter": {
        "isRequired": function () {}
      },
      "filterFormatted": {
        "isRequired": function () {}
      },
      "filterValue": {
        "isRequired": function () {}
      },
      "formatExtraData": {
        "isRequired": function () {}
      },
      "headerAlign": {
        "isRequired": function () {}
      },
      "headerText": {
        "isRequired": function () {}
      },
      "headerTitle": {
        "isRequired": function () {}
      },
      "hidden": {
        "isRequired": function () {}
      },
      "hiddenOnInsert": {
        "isRequired": function () {}
      },
      "invalidEditColumnClassName": {
        "isRequired": function () {}
      },
      "isKey": {
        "isRequired": function () {}
      },
      "keyValidator": {
        "isRequired": function () {}
      },
      "onSort": {
        "isRequired": function () {}
      },
      "searchable": {
        "isRequired": function () {}
      },
      "sort": {
        "isRequired": function () {}
      },
      "sortFunc": {
        "isRequired": function () {}
      },
      "sortFuncExtraData": {
        "isRequired": function () {}
      },
      "sortHeaderColumnClassName": {
        "isRequired": function () {}
      },
      "sortIndicator": {
        "isRequired": function () {}
      },
      "tdAttr": {
        "isRequired": function () {}
      },
      "tdStyle": {
        "isRequired": function () {}
      },
      "thStyle": {
        "isRequired": function () {}
      },
      "width": {
        "isRequired": function () {}
      }
    }
  }
};
ReactBootstrapTable.BootstrapTable.prototype = {
  "forceUpdate": function () {},
  "isReactComponent": function () {},
  "setState": function () {}
};
ReactBootstrapTable.ButtonGroup.prototype = {
  "forceUpdate": function () {},
  "isReactComponent": function () {},
  "setState": function () {}
};
ReactBootstrapTable.ClearSearchButton.prototype = {
  "forceUpdate": function () {},
  "isReactComponent": function () {},
  "setState": function () {}
};
ReactBootstrapTable.DeleteButton.prototype = {
  "forceUpdate": function () {},
  "isReactComponent": function () {},
  "setState": function () {}
};
ReactBootstrapTable.ExportCSVButton.prototype = {
  "forceUpdate": function () {},
  "isReactComponent": function () {},
  "setState": function () {}
};
ReactBootstrapTable.InsertButton.prototype = {
  "forceUpdate": function () {},
  "isReactComponent": function () {},
  "setState": function () {}
};
ReactBootstrapTable.InsertModalBody.prototype = {
  "forceUpdate": function () {},
  "isReactComponent": function () {},
  "setState": function () {}
};
ReactBootstrapTable.InsertModalFooter.prototype = {
  "forceUpdate": function () {},
  "isReactComponent": function () {},
  "setState": function () {}
};
ReactBootstrapTable.InsertModalHeader.prototype = {
  "forceUpdate": function () {},
  "isReactComponent": function () {},
  "setState": function () {}
};
ReactBootstrapTable.SearchField.prototype = {
  "forceUpdate": function () {},
  "isReactComponent": function () {},
  "setState": function () {}
};
ReactBootstrapTable.ShowSelectedOnlyButton.prototype = {
  "forceUpdate": function () {},
  "isReactComponent": function () {},
  "setState": function () {}
};
ReactBootstrapTable.SizePerPageDropDown.prototype = {
  "forceUpdate": function () {},
  "isReactComponent": function () {},
  "setState": function () {}
};
ReactBootstrapTable.TableHeaderColumn.prototype = {
  "forceUpdate": function () {},
  "isReactComponent": function () {},
  "setState": function () {}
};
/**********************************************************************
 * End Generated Extern for ReactBootstrapTable
/**********************************************************************/
