/**********************************************************************
 * Extern for ReactBootstrapTypeahead
 * Generated by http://jmmk.github.io/javascript-externs-generator
 **********************************************************************/
var ReactBootstrapTypeahead = {
  "AsyncTypeahead": {
    "defaultProps": {
      "delay": {},
      "minLength": {},
      "options": {},
      "promptText": {},
      "searchText": {},
      "useCache": {}
    },
    "propTypes": {
      "delay": {
        "isRequired": function () {}
      },
      "isLoading": function () {},
      "onSearch": function () {},
      "options": {
        "isRequired": function () {}
      },
      "promptText": {
        "isRequired": function () {}
      },
      "searchText": {
        "isRequired": function () {}
      },
      "useCache": {
        "isRequired": function () {}
      }
    }
  },
  "Highlighter": {
    "propTypes": {
      "children": function () {},
      "search": function () {}
    }
  },
  "Menu": {
    "defaultProps": {
      "align": {},
      "maxHeight": {},
      "paginate": {},
      "paginationText": {}
    },
    "propTypes": {
      "align": {
        "isRequired": function () {}
      },
      "maxHeight": {
        "isRequired": function () {}
      },
      "paginationText": {
        "isRequired": function () {}
      }
    }
  },
  "MenuItem": {
    "contextTypes": {
      "activeIndex": function () {},
      "isOnlyResult": function () {},
      "onActiveItemChange": function () {},
      "onInitialItemChange": function () {},
      "onMenuItemClick": function () {}
    },
    "displayName": {},
    "propTypes": {
      "option": function () {},
      "position": {
        "isRequired": function () {}
      }
    }
  },
  "Token": {
    "defaultProps": {
      "eventTypes": {},
      "excludeScrollbar": {},
      "outsideClickIgnoreClass": {},
      "preventDefault": {},
      "stopPropagation": {}
    },
    "displayName": {},
    "getClass": function () {}
  },
  "Typeahead": {
    "defaultProps": {
      "eventTypes": {},
      "excludeScrollbar": {},
      "outsideClickIgnoreClass": {},
      "preventDefault": {},
      "stopPropagation": {}
    },
    "displayName": {},
    "getClass": function () {}
  },
  "asyncContainer": function () {},
  "menuItemContainer": function () {},
  "tokenContainer": function () {}
};
ReactBootstrapTypeahead.AsyncTypeahead.prototype = {
  "forceUpdate": function () {},
  "isReactComponent": function () {},
  "setState": function () {}
};
ReactBootstrapTypeahead.Highlighter.prototype = {
  "forceUpdate": function () {},
  "isReactComponent": function () {},
  "setState": function () {}
};
ReactBootstrapTypeahead.Menu.prototype = {
  "forceUpdate": function () {},
  "isReactComponent": function () {},
  "setState": function () {}
};
ReactBootstrapTypeahead.MenuItem.prototype = {
  "forceUpdate": function () {},
  "isReactComponent": function () {},
  "setState": function () {}
};
ReactBootstrapTypeahead.Token.prototype = {
  "componentDidMount": function () {},
  "componentDidUpdate": function () {},
  "componentWillUnmount": function () {},
  "constructor": function () {},
  "forceUpdate": function () {},
  "getInstance": function () {},
  "isReactComponent": function () {},
  "render": function () {},
  "setState": function () {}
};
ReactBootstrapTypeahead.Typeahead.prototype = {
  "componentDidMount": function () {},
  "componentDidUpdate": function () {},
  "componentWillUnmount": function () {},
  "constructor": function () {},
  "forceUpdate": function () {},
  "getInstance": function () {},
  "isReactComponent": function () {},
  "render": function () {},
  "setState": function () {}
};
/**********************************************************************
 * End Generated Extern for ReactBootstrapTypeahead
/**********************************************************************/