/**********************************************************************
 * Extern for ReactBootstrapTypeahead
 * Generated by http://jmmk.github.io/javascript-externs-generator
 **********************************************************************/
var ReactBootstrapTypeahead = {
  "AsyncTypeahead": {
    "defaultProps": {
      "delay": {},
      "minLength": {},
      "options": {},
      "promptText": {},
      "searchText": {},
      "useCache": {}
    },
    "propTypes": {
      "delay": {
        "isRequired": function () {}
      },
      "onSearch": function () {},
      "options": {
        "isRequired": function () {}
      },
      "promptText": {
        "isRequired": function () {}
      },
      "searchText": {
        "isRequired": function () {}
      },
      "useCache": {
        "isRequired": function () {}
      }
    }
  },
  "Menu": {
    "PropTypes": {
      "align": {
        "isRequired": function () {}
      },
      "emptyLabel": {
        "isRequired": function () {}
      },
      "maxHeight": {
        "isRequired": function () {}
      },
      "paginationText": {
        "isRequired": function () {}
      }
    },
    "defaultProps": {
      "align": {},
      "emptyLabel": {},
      "maxHeight": {},
      "paginate": {},
      "paginationText": {}
    }
  },
  "MenuItem": {
    "contextTypes": {
      "activeIndex": function () {},
      "onActiveItemChange": function () {},
      "onInitialItemChange": function () {},
      "onMenuItemClick": function () {}
    },
    "displayName": {},
    "propTypes": {
      "option": function () {},
      "position": {
        "isRequired": function () {}
      }
    }
  },
  "Token": {
    "defaultProps": {
      "excludeScrollbar": {}
    },
    "displayName": {},
    "getClass": function () {},
    "getDefaultProps": {
      "isReactClassApproved": {}
    }
  },
  "Typeahead": {
    "defaultProps": {
      "excludeScrollbar": {}
    },
    "displayName": {},
    "getClass": function () {},
    "getDefaultProps": {
      "isReactClassApproved": {}
    }
  },
  "asyncContainer": function () {},
  "menuItemContainer": function () {},
  "tokenContainer": function () {}
};
ReactBootstrapTypeahead.AsyncTypeahead.prototype = {
  "forceUpdate": function () {},
  "isReactComponent": function () {},
  "setState": function () {}
};
ReactBootstrapTypeahead.Menu.prototype = {
  "forceUpdate": function () {},
  "isReactComponent": function () {},
  "setState": function () {}
};
ReactBootstrapTypeahead.MenuItem.prototype = {
  "forceUpdate": function () {},
  "isReactComponent": function () {},
  "setState": function () {}
};
ReactBootstrapTypeahead.Token.prototype = {
  "__outsideClickHandler": function () {},
  "__reactAutoBindPairs": function () {},
  "childContextTypes": function () {},
  "componentDidMount": function () {},
  "componentDidUpdate": function () {},
  "componentWillMount": function () {},
  "componentWillReceiveProps": function () {},
  "componentWillUnmount": function () {},
  "componentWillUpdate": function () {},
  "constructor": function () {},
  "contextTypes": function () {},
  "disableOnClickOutside": function () {},
  "enableOnClickOutside": function () {},
  "forceUpdate": function () {},
  "getChildContext": function () {},
  "getDefaultProps": function () {},
  "getInitialState": function () {},
  "getInstance": function () {},
  "isMounted": function () {},
  "isReactComponent": function () {},
  "mixins": function () {},
  "propTypes": function () {},
  "render": function () {},
  "replaceState": function () {},
  "setState": function () {},
  "shouldComponentUpdate": function () {},
  "statics": function () {},
  "updateComponent": function () {}
};
ReactBootstrapTypeahead.Typeahead.prototype = {
  "__outsideClickHandler": function () {},
  "__reactAutoBindPairs": function () {},
  "childContextTypes": function () {},
  "componentDidMount": function () {},
  "componentDidUpdate": function () {},
  "componentWillMount": function () {},
  "componentWillReceiveProps": function () {},
  "componentWillUnmount": function () {},
  "componentWillUpdate": function () {},
  "constructor": function () {},
  "contextTypes": function () {},
  "disableOnClickOutside": function () {},
  "enableOnClickOutside": function () {},
  "forceUpdate": function () {},
  "getChildContext": function () {},
  "getDefaultProps": function () {},
  "getInitialState": function () {},
  "getInstance": function () {},
  "isMounted": function () {},
  "isReactComponent": function () {},
  "mixins": function () {},
  "propTypes": function () {},
  "render": function () {},
  "replaceState": function () {},
  "setState": function () {},
  "shouldComponentUpdate": function () {},
  "statics": function () {},
  "updateComponent": function () {}
};
/**********************************************************************
 * End Generated Extern for ReactBootstrapTypeahead
/**********************************************************************/
