/**********************************************************************
 * Extern for rc-slider
 * Generated by http://jmmk.github.io/javascript-externs-generator
 **********************************************************************/
var RcSlider = {
  "Handle": {
    "propTypes": {
      "className": {
        "isRequired": function () {}
      },
      "disabled": {
        "isRequired": function () {}
      },
      "max": {
        "isRequired": function () {}
      },
      "min": {
        "isRequired": function () {}
      },
      "offset": {
        "isRequired": function () {}
      },
      "style": {
        "isRequired": function () {}
      },
      "value": {
        "isRequired": function () {}
      },
      "vertical": {
        "isRequired": function () {}
      }
    }
  },
  "Range": {
    "defaultProps": {
      "activeDotStyle": {},
      "allowCross": {},
      "className": {},
      "count": {},
      "disabled": {},
      "dotStyle": {},
      "dots": {},
      "handle": function () {},
      "handleStyle": {},
      "included": {},
      "marks": {},
      "max": {},
      "min": {},
      "onAfterChange": function () {},
      "onBeforeChange": function () {},
      "onChange": function () {},
      "prefixCls": {},
      "pushable": {},
      "railStyle": {},
      "step": {},
      "trackStyle": {},
      "vertical": {}
    },
    "displayName": {},
    "propTypes": {
      "activeDotStyle": {
        "isRequired": function () {}
      },
      "allowCross": {
        "isRequired": function () {}
      },
      "children": {
        "isRequired": function () {}
      },
      "className": {
        "isRequired": function () {}
      },
      "count": {
        "isRequired": function () {}
      },
      "defaultValue": {
        "isRequired": function () {}
      },
      "disabled": {
        "isRequired": function () {}
      },
      "dotStyle": {
        "isRequired": function () {}
      },
      "dots": {
        "isRequired": function () {}
      },
      "handle": {
        "isRequired": function () {}
      },
      "handleStyle": {
        "isRequired": function () {}
      },
      "included": {
        "isRequired": function () {}
      },
      "marks": {
        "isRequired": function () {}
      },
      "max": {
        "isRequired": function () {}
      },
      "maximumTrackStyle": {
        "isRequired": function () {}
      },
      "min": {
        "isRequired": function () {}
      },
      "minimumTrackStyle": {
        "isRequired": function () {}
      },
      "onAfterChange": {
        "isRequired": function () {}
      },
      "onBeforeChange": {
        "isRequired": function () {}
      },
      "onChange": {
        "isRequired": function () {}
      },
      "prefixCls": {
        "isRequired": function () {}
      },
      "pushable": {
        "isRequired": function () {}
      },
      "railStyle": {
        "isRequired": function () {}
      },
      "step": {
        "isRequired": function () {}
      },
      "style": {
        "isRequired": function () {}
      },
      "trackStyle": {
        "isRequired": function () {}
      },
      "value": {
        "isRequired": function () {}
      },
      "vertical": {
        "isRequired": function () {}
      }
    }
  },
  "createSliderWithTooltip": function () {},
  "default": {
    "Handle": {
      "propTypes": {
        "className": {
          "isRequired": function () {}
        },
        "disabled": {
          "isRequired": function () {}
        },
        "max": {
          "isRequired": function () {}
        },
        "min": {
          "isRequired": function () {}
        },
        "offset": {
          "isRequired": function () {}
        },
        "style": {
          "isRequired": function () {}
        },
        "value": {
          "isRequired": function () {}
        },
        "vertical": {
          "isRequired": function () {}
        }
      }
    },
    "Range": {
      "defaultProps": {
        "activeDotStyle": {},
        "allowCross": {},
        "className": {},
        "count": {},
        "disabled": {},
        "dotStyle": {},
        "dots": {},
        "handle": function () {},
        "handleStyle": {},
        "included": {},
        "marks": {},
        "max": {},
        "min": {},
        "onAfterChange": function () {},
        "onBeforeChange": function () {},
        "onChange": function () {},
        "prefixCls": {},
        "pushable": {},
        "railStyle": {},
        "step": {},
        "trackStyle": {},
        "vertical": {}
      },
      "displayName": {},
      "propTypes": {
        "activeDotStyle": {
          "isRequired": function () {}
        },
        "allowCross": {
          "isRequired": function () {}
        },
        "children": {
          "isRequired": function () {}
        },
        "className": {
          "isRequired": function () {}
        },
        "count": {
          "isRequired": function () {}
        },
        "defaultValue": {
          "isRequired": function () {}
        },
        "disabled": {
          "isRequired": function () {}
        },
        "dotStyle": {
          "isRequired": function () {}
        },
        "dots": {
          "isRequired": function () {}
        },
        "handle": {
          "isRequired": function () {}
        },
        "handleStyle": {
          "isRequired": function () {}
        },
        "included": {
          "isRequired": function () {}
        },
        "marks": {
          "isRequired": function () {}
        },
        "max": {
          "isRequired": function () {}
        },
        "maximumTrackStyle": {
          "isRequired": function () {}
        },
        "min": {
          "isRequired": function () {}
        },
        "minimumTrackStyle": {
          "isRequired": function () {}
        },
        "onAfterChange": {
          "isRequired": function () {}
        },
        "onBeforeChange": {
          "isRequired": function () {}
        },
        "onChange": {
          "isRequired": function () {}
        },
        "prefixCls": {
          "isRequired": function () {}
        },
        "pushable": {
          "isRequired": function () {}
        },
        "railStyle": {
          "isRequired": function () {}
        },
        "step": {
          "isRequired": function () {}
        },
        "style": {
          "isRequired": function () {}
        },
        "trackStyle": {
          "isRequired": function () {}
        },
        "value": {
          "isRequired": function () {}
        },
        "vertical": {
          "isRequired": function () {}
        }
      }
    },
    "createSliderWithTooltip": function () {},
    "defaultProps": {
      "activeDotStyle": {},
      "className": {},
      "disabled": {},
      "dotStyle": {},
      "dots": {},
      "handle": function () {},
      "handleStyle": {},
      "included": {},
      "marks": {},
      "max": {},
      "min": {},
      "onAfterChange": function () {},
      "onBeforeChange": function () {},
      "onChange": function () {},
      "prefixCls": {},
      "railStyle": {},
      "step": {},
      "trackStyle": {},
      "vertical": {}
    },
    "displayName": {},
    "propTypes": {
      "activeDotStyle": {
        "isRequired": function () {}
      },
      "children": {
        "isRequired": function () {}
      },
      "className": {
        "isRequired": function () {}
      },
      "defaultValue": {
        "isRequired": function () {}
      },
      "disabled": {
        "isRequired": function () {}
      },
      "dotStyle": {
        "isRequired": function () {}
      },
      "dots": {
        "isRequired": function () {}
      },
      "handle": {
        "isRequired": function () {}
      },
      "handleStyle": {
        "isRequired": function () {}
      },
      "included": {
        "isRequired": function () {}
      },
      "marks": {
        "isRequired": function () {}
      },
      "max": {
        "isRequired": function () {}
      },
      "maximumTrackStyle": {
        "isRequired": function () {}
      },
      "min": {
        "isRequired": function () {}
      },
      "minimumTrackStyle": {
        "isRequired": function () {}
      },
      "onAfterChange": {
        "isRequired": function () {}
      },
      "onBeforeChange": {
        "isRequired": function () {}
      },
      "onChange": {
        "isRequired": function () {}
      },
      "prefixCls": {
        "isRequired": function () {}
      },
      "railStyle": {
        "isRequired": function () {}
      },
      "step": {
        "isRequired": function () {}
      },
      "style": {
        "isRequired": function () {}
      },
      "trackStyle": {
        "isRequired": function () {}
      },
      "value": {
        "isRequired": function () {}
      },
      "vertical": {
        "isRequired": function () {}
      }
    }
  }
};
RcSlider.Handle.prototype = {
  "forceUpdate": function () {},
  "isReactComponent": function () {},
  "setState": function () {}
};
RcSlider.Range.prototype = {
  "forceUpdate": function () {},
  "isReactComponent": function () {},
  "setState": function () {}
};
RcSlider.default.prototype = {
  "forceUpdate": function () {},
  "isReactComponent": function () {},
  "setState": function () {}
};
RcSlider.default.Handle.prototype = {
  "forceUpdate": function () {},
  "isReactComponent": function () {},
  "setState": function () {}
};
RcSlider.default.Range.prototype = {
  "forceUpdate": function () {},
  "isReactComponent": function () {},
  "setState": function () {}
};
/**********************************************************************
 * End Generated Extern for rc-slider
/**********************************************************************/
